name: Veracode Build Ruby Application

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
      token:
        required: true
        type: string
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}

    - uses: actions/checkout@v4
      with:
        path: 'veracode-helper'

    # - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
    #   with:
    #     ruby-version: '3.1' # Not needed with a .ruby-version file
    # - run: bundle install
    # - run: bundle exec rake
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.80.0
      with:
        ruby-version: 2.6.6

    - uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: install

    - name: Install Dependencies
      run: |
        sudo apt install -yqq libpq-dev
        gem install bundler

    - name: Install Gems
      run: |
        bundle install

    - name: Package the application
      env:
        VERACODE_API_KEY_ID: '${{ secrets.VERACODE_API_ID }}'
        VERACODE_API_KEY_SECRET: '${{ secrets.VERACODE_API_KEY }}'
      run: |
        cd veracode-helper/helper/cli
        cliFile=$(ls -1 . | head -n 1)
        cliFileName=$(echo "$cliFile" | cut -c 1-$((${#cliFile}-7)))
        tar -zxvf $cliFile
        cd $cliFileName
        chmod +x install.sh
        ./install.sh system
        cd /home/runner/work/veracode/veracode/
        veracode package --source . --output veracode-artifacts --trust
        zip veracode-artifact.zip veracode-artifacts/* -x .zip .tar .tar.gz .gz

    - uses: actions/upload-artifact@v4
      with:
        name: veracode-artifact
        path: veracode-artifact.zip
